# Generated by Django 2.2.3 on 2020-03-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200301_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('csa', 'CS'), ('it', 'IT'), ('ce', 'CE'), ('me', 'ME'), ('ec', 'EC'), ('ee', 'EE')], default='cs', max_length=10),
        ),
    ]
