# Generated by Django 3.0.4 on 2020-04-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200320_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(choices=[('hod', 'Hod'), ('faculty', 'Faculty')], default='faculty', max_length=30),
        ),
    ]
