# Generated by Django 3.0.4 on 2020-04-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200410_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='account',
            field=models.BooleanField(default=False),
        ),
    ]
