# Generated by Django 3.0.4 on 2020-04-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200410_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='District',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='city_town_area',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='state',
        ),
    ]
