# Generated by Django 3.0.4 on 2020-05-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200427_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='sec',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2),
        ),
    ]
