# Generated by Django 3.0.4 on 2020-05-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_studentprofile_sec'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='join_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
