# Generated by Django 3.0.6 on 2020-09-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterDownload',
            fields=[
                ('link_name', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=50, primary_key=True, serialize=False, unique=True)),
                ('link', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='#', max_length=150)),
            ],
        ),
    ]
