# Generated by Django 3.0.6 on 2020-09-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerdownload',
            name='link',
            field=models.CharField(choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('google', 'google'), ('linkdin', 'linkdin'), ('twitter', 'twitter'), ('wiki', 'wiki'), ('youtube', 'youtube'), ('pinterest', 'pinterest'), ('tumblr', 'tumblr')], default='#', max_length=150),
        ),
        migrations.AlterField(
            model_name='footerdownload',
            name='link_name',
            field=models.CharField(choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('google', 'google'), ('linkdin', 'linkdin'), ('twitter', 'twitter'), ('wiki', 'wiki'), ('youtube', 'youtube'), ('pinterest', 'pinterest'), ('tumblr', 'tumblr')], max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
