# Generated by Django 3.0.6 on 2020-09-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20200930_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerdownload',
            name='link',
            field=models.CharField(default='#', max_length=150),
        ),
    ]
