# Generated by Django 3.0.6 on 2020-10-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_auto_20200930_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerdownload',
            name='link_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
