# Generated by Django 3.0.6 on 2020-10-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_auto_20201001_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_cate', models.CharField(choices=[('download', 'download'), ('quick_link', 'quick_link'), ('suggest_link', 'suggest_link'), ('sister_concern', 'sister_concern')], max_length=50)),
                ('link_name', models.CharField(max_length=50)),
                ('link', models.CharField(default='#', max_length=150)),
            ],
            options={
                'unique_together': {('link_cate', 'link_name')},
            },
        ),
        migrations.DeleteModel(
            name='FooterDownload',
        ),
    ]
