# Generated by Django 3.0.6 on 2020-10-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_auto_20201001_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carausal',
            fields=[
                ('slide_no', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='admin/website/carausal/')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
