# Generated by Django 3.0.6 on 2020-06-15 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200615_2147'),
        ('hod', '0002_subject_sem_subject_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject_sem',
            unique_together={('year', 'subject_code')},
        ),
    ]
