# Generated by Django 3.0.6 on 2020-06-16 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200615_2147'),
        ('hod', '0003_auto_20200615_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(choices=[('cs', 'CS'), ('it', 'IT'), ('ce', 'CE'), ('me', 'ME'), ('ec', 'EC'), ('ee', 'EE')], default='cs', max_length=10)),
                ('sem', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII'), ('8', 'VIII')], default='I', max_length=2)),
                ('file', models.FileField(upload_to='syllabus/%Y')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.batch')),
            ],
            options={
                'unique_together': {('year', 'dept', 'sem')},
            },
        ),
    ]
