# Generated by Django 3.0.6 on 2020-06-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200615_2147'),
        ('hod', '0004_syllabus'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject_sem',
            unique_together={('year', 'dept', 'sem', 'subject_code')},
        ),
    ]
