# Generated by Django 3.0.6 on 2020-06-17 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hod', '0005_auto_20200617_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignCT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hod.Class')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hod.Subject_sem')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
