# Generated by Django 3.0.6 on 2020-06-17 21:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hod', '0006_assignct'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignct',
            unique_together={('class_id', 'subject_id', 'teacher_id')},
        ),
    ]
