# Generated by Django 3.0.6 on 2020-07-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0007_auto_20200618_0234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignct',
            unique_together={('class_id', 'subject_id')},
        ),
    ]
