# Generated by Django 3.0.6 on 2020-08-26 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200615_2147'),
        ('hod', '0009_teachersubjectattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubjectTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_no', models.IntegerField()),
                ('unit_no', models.IntegerField()),
                ('total_mark', models.FloatField()),
                ('obtain_mark', models.FloatField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hod.Subject_sem')),
            ],
            options={
                'unique_together': {('student_id', 'subject_id', 'tutorial_no', 'unit_no')},
            },
        ),
    ]
