# Generated by Django 3.0.6 on 2020-08-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200615_2147'),
        ('hod', '0010_teachersubjecttutorial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherSubjectTutorial',
            new_name='TeacherSubjectMark',
        ),
    ]
