# Generated by Django 3.0.6 on 2020-08-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200615_2147'),
        ('hod', '0011_auto_20200826_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubjectmark',
            name='exam_no',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=0),
        ),
        migrations.AddField(
            model_name='teachersubjectmark',
            name='exam_type',
            field=models.CharField(choices=[('tutorial', 'tutorial'), ('test', 'test')], default='tutorial', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='teachersubjectmark',
            unique_together={('student_id', 'subject_id', 'exam_type', 'exam_no', 'unit_no')},
        ),
        migrations.RemoveField(
            model_name='teachersubjectmark',
            name='tutorial_no',
        ),
    ]
