# Generated by Django 3.0.6 on 2020-08-26 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200615_2147'),
        ('hod', '0012_auto_20200826_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubjectMidTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_no', models.IntegerField(choices=[(1, 1), (2, 2)], default=0)),
                ('total_mark', models.FloatField()),
                ('obtain_mark', models.FloatField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hod.Subject_sem')),
            ],
        ),
    ]
