# Generated by Django 3.0.6 on 2020-09-04 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200615_2147'),
        ('hod', '0015_teacherprojectmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherpracticalmark',
            unique_together={('student_id', 'subject_id', 'practical_no')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherprojectmark',
            unique_together={('student_id', 'subject_id', 'project_type')},
        ),
        migrations.AlterUniqueTogether(
            name='teachersubjectmidterm',
            unique_together={('student_id', 'subject_id', 'exam_no')},
        ),
    ]
