# Generated by Django 3.0.6 on 2020-09-04 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200615_2147'),
        ('hod', '0016_auto_20200904_1039'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherprojectmark',
            unique_together={('student_id', 'subject_id')},
        ),
        migrations.RemoveField(
            model_name='teacherprojectmark',
            name='project_type',
        ),
    ]
