# Generated by Django 3.0.4 on 2020-04-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sem',
        ),
    ]
