# Generated by Django 3.0.4 on 2020-05-01 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_sem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII'), ('8', 'VIII')], default='I', max_length=5)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_attendance', to='student.Student')),
            ],
            options={
                'unique_together': {('enrollment', 'sem')},
            },
        ),
    ]
