# Generated by Django 3.0.4 on 2020-05-07 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_totalattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor_Gaurdian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('cs', 'CS'), ('it', 'IT'), ('ce', 'CE'), ('me', 'ME'), ('ec', 'EC'), ('ee', 'EE')], default='cs', max_length=10)),
                ('sec', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=2)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.batch')),
            ],
        ),
    ]
