# Generated by Django 3.0.4 on 2020-05-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_tutor_gaurdian'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutor_Gaurdian',
        ),
    ]
