# Generated by Django 3.0.6 on 2020-05-15 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0006_delete_tutor_gaurdian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tgcalling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII'), ('8', 'VIII')], default='I', max_length=2)),
                ('date', models.DateField(default='')),
                ('contact_no', models.CharField(default='', max_length=10)),
                ('contact_person', models.CharField(default='', max_length=50)),
                ('reason', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_calling', to='student.Student')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('enrollment', 'date')},
            },
        ),
    ]
