# Generated by Django 3.0.6 on 2020-06-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_tgcalling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalattendance',
            name='sem',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII'), ('8', 'VIII')], default='I', max_length=6),
        ),
    ]
