# Generated by Django 3.0.6 on 2020-09-07 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20200907_0605'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='batch',
            managers=[
            ],
        ),
    ]
