# Generated by Django 3.0.6 on 2020-09-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20200907_0606'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentmidsem',
            unique_together={('enrollment', 'sem', 'midterm')},
        ),
        migrations.AlterUniqueTogether(
            name='studentresult',
            unique_together={('enrollment', 'sem')},
        ),
    ]
