# Generated by Django 3.0.6 on 2020-09-08 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20200908_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('x', 'x'), ('xii', 'xii'), ('diploma', 'diploma'), ('jee', 'jee'), ('gate', 'gate'), ('ug', 'ug'), ('pg', 'pg'), ('other', 'other')], default='tenth', max_length=50)),
                ('roll_no', models.CharField(default='', max_length=50)),
                ('rank', models.IntegerField(default='')),
                ('board', models.CharField(default='', max_length=50)),
                ('year_of_passing', models.IntegerField(default='')),
                ('total_mark', models.FloatField(default='')),
                ('obtain_mark', models.FloatField(default='')),
                ('percent', models.FloatField(default='')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_education', to='student.Student')),
            ],
            options={
                'unique_together': {('enrollment', 'course')},
            },
        ),
    ]
