# Generated by Django 3.0.6 on 2020-09-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_studenteducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenteducation',
            name='marksheet',
            field=models.FileField(default='', upload_to='student/marksheet/%Y/'),
        ),
    ]
