# Generated by Django 3.0.6 on 2020-09-08 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_studenteducation_marksheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenteducation',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_education', to='student.Student'),
        ),
    ]
