# Generated by Django 3.0.6 on 2020-09-14 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20200909_0225'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentfee',
            unique_together={('enrollment', 'receipt_no')},
        ),
    ]
