# Generated by Django 3.0.6 on 2020-09-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20200914_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu_detail_12',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='stu_detail_diploma',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='stu_detail_jee',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='stu_detail_other',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='stu_detail_pg',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='stu_detail_ug',
            name='enrollment',
        ),
        migrations.DeleteModel(
            name='Stu_detail_10',
        ),
        migrations.DeleteModel(
            name='Stu_detail_12',
        ),
        migrations.DeleteModel(
            name='Stu_detail_diploma',
        ),
        migrations.DeleteModel(
            name='Stu_detail_jee',
        ),
        migrations.DeleteModel(
            name='Stu_detail_other',
        ),
        migrations.DeleteModel(
            name='Stu_detail_pg',
        ),
        migrations.DeleteModel(
            name='Stu_detail_ug',
        ),
    ]
