# Generated by Django 3.0.6 on 2020-09-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20200914_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='week',
            field=models.IntegerField(default=0),
        ),
    ]
