# Generated by Django 3.0.6 on 2020-10-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_student_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.CharField(max_length=200)),
            ],
        ),
    ]
