# Generated by Django 3.0.6 on 2020-10-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_attendancemessages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancemessages',
            name='id',
        ),
        migrations.AddField(
            model_name='attendancemessages',
            name='message_type',
            field=models.CharField(choices=[('suspension', 'suspension'), ('attendance', 'attendance')], default='suspension', max_length=30, primary_key=True, serialize=False),
        ),
    ]
