# Generated by Django 3.0.6 on 2020-10-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20201001_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemessages',
            name='message_type',
            field=models.CharField(choices=[('suspension', 'suspension'), ('attendance', 'attendance'), ('warning', 'warning')], default='suspension', max_length=30, primary_key=True, serialize=False),
        ),
    ]
